"""Type stubs for google.cloud.datastore.key"""

from typing import Any, Dict, List, Optional, Tuple, Union

from google.cloud.datastore_v1.types import entity as _entity_pb2

class Key:
    """An immutable representation of a datastore Key."""

    _flat_path: Tuple[Union[str, int], ...]
    _parent: Optional[Key]
    _namespace: Optional[str]
    _database: Optional[str]
    _project: str
    _path: List[Dict[str, Any]]

    def __init__(
        self,
        *path_args: Union[str, int],
        parent: Optional[Key] = ...,
        namespace: Optional[str] = ...,
        project: Optional[str] = ...,
        database: Optional[str] = ...
    ) -> None: ...

    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

    @staticmethod
    def _parse_path(path_args: Tuple[Union[str, int], ...]) -> List[Dict[str, Any]]: ...

    def _combine_args(self) -> List[Dict[str, Any]]: ...
    def _clone(self) -> Key: ...
    def _make_parent(self) -> Optional[Key]: ...

    def completed_key(self, id_or_name: Union[str, int]) -> Key: ...
    def to_protobuf(self) -> _entity_pb2.Key: ...
    def to_legacy_urlsafe(self, location_prefix: Optional[str] = ...) -> bytes: ...

    @classmethod
    def from_legacy_urlsafe(cls, urlsafe: Union[bytes, str]) -> Key: ...

    @property
    def is_partial(self) -> bool: ...

    @property
    def database(self) -> Optional[str]: ...

    @property
    def namespace(self) -> Optional[str]: ...

    @property
    def path(self) -> List[Dict[str, Any]]: ...

    @property
    def flat_path(self) -> Tuple[Union[str, int], ...]: ...

    @property
    def kind(self) -> str: ...

    @property
    def id(self) -> Optional[int]: ...

    @property
    def name(self) -> Optional[str]: ...

    @property
    def id_or_name(self) -> Optional[Union[int, str]]: ...

    @property
    def project(self) -> str: ...

    @property
    def parent(self) -> Optional[Key]: ...

def _validate_project(project: Optional[str], parent: Optional[Key]) -> Optional[str]: ...
def _clean_app(app_str: str) -> str: ...
def _get_empty(value: Any, empty_value: Any) -> Optional[Any]: ...
def _check_database_id(database_id: Optional[str]) -> None: ...
def _add_id_or_name(flat_path: List[Union[str, int]], element_pb: Any, empty_allowed: bool) -> None: ...
def _get_flat_path(path_pb: Any) -> Tuple[Union[str, int], ...]: ...
def _to_legacy_path(dict_path: List[Dict[str, Any]]) -> Any: ...
